$[5 ~ 7 ~ 9 ~ 11 ~ 13 ~ 15 ~ 17 ~ 19]$

In [1]:
import torch
import numpy as np


X = torch.Tensor([5, 7, 9, 11, 13, 15, 17, 19])
Y = np.array([5, 7, 9, 11, 13, 15, 17, 19])
print(X)
print(Y)

tensor([ 5.,  7.,  9., 11., 13., 15., 17., 19.])
[ 5  7  9 11 13 15 17 19]


$
\left(
\begin{array}{ccc}
1 & 2  & 3\\
4  & 5 & 6
\end{array}
\right)
$

In [26]:
A = torch.Tensor([
    [1, 2, 3],
    [4, 5, 6]])
B = np.array([
    [1, 2, 3],
    [4, 5, 6]])
print(A)
print(B)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
[[1 2 3]
 [4 5 6]]


In [4]:
print(A.shape)
print(B.shape)

torch.Size([2, 3])
(2, 3)


In [14]:
print(A.nelement())
print(B.size)

6
6


In [16]:
A.size(1)

3

In [17]:
print(A.dim())
print(B.ndim)

2
2


In [21]:
A.nonzero()
# print(A)

tensor([[0, 0],
        [0, 1],
        [0, 2]])

In [22]:
A_exp = A.exp()
B_exp = np.exp(B)
print(A_exp)
print(B_exp)

tensor([[ 2.7183,  7.3891, 20.0855],
        [ 1.0000,  1.0000,  1.0000]])
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


$\sqrt{e^{X_{n}}+2}$

In [24]:
print((A.exp() + 2).sqrt())

tensor([[2.1722, 3.0642, 4.6995],
        [1.7321, 1.7321, 1.7321]])


$||\bar{v}|| = \sqrt{x_{1}^{2}+x_{2}^{2}+...+x_{n}^{2}}$

In [28]:
print(A)
print((A**2).sum(1).sqrt())

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([3.7417, 8.7750])


$\bar{X} = \frac{\Sigma X}{N}$

In [ ]:
def vector_mean(array):
    n = len(array)
    i = 0
    for element in array:
        i = i + element
    mean = i/n
    return mean

def des_estandar(array):
    n = len(array)
    mu = vector_mean(array)
    i = 0
    for

array = [1, 1, 1, 1, 1]

print(vector_mean(array))

$\sigma = \sqrt{\frac{1}{N} \sum_{i=1}^{N}(x_{i}-\mu)^{2}}$

In [33]:
v1 = [4, 8, 9, 15, 27]
v2 = [1, 1, 2, 2]
v3 = [0, 9, 14, 23, 28, 37, 2]
print(np.std(v1))
print(np.std(v2))
print(np.std(v3))

8.01498596380555
0.5
12.755151020314122
